---
- name: PHP | Install EPEL repository (required for some PHP extensions)
  yum:
    name: epel-release
    state: present

- name: PHP | Install PHP packages
  yum:
    name: "php-{{ item }}"
    state: present
  loop:
    - mysqlnd
    - fpm
    - cli

- name: PHP | Ensure PHP-FPM is started and enabled
  ansible.builtin.service:
    name: "php-fpm"
    state: started
    enabled: yes

- name: PHP | Ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
